-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS email_messages.email_gmail
(
    em_id integer NOT NULL,
    headers jsonb,
    gmail_api_thread_id text COLLATE pg_catalog."default" NOT NULL,
    gmail_api_id text COLLATE pg_catalog."default" NOT NULL,
    json_object jsonb,
    CONSTRAINT email_gmail_pk PRIMARY KEY (em_id),
    CONSTRAINT email_gmail_unique UNIQUE (gmail_api_id)
);

CREATE TABLE IF NOT EXISTS email_messages.email_hotmail
(
    em_id integer NOT NULL,
    headers jsonb,
    json_object jsonb
);

CREATE TABLE IF NOT EXISTS email_messages.email_message_general
(
    em_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email_client text COLLATE pg_catalog."default" NOT NULL,
    email_id bigint NOT NULL,
    email_message_id text COLLATE pg_catalog."default" NOT NULL,
    has_attachment boolean DEFAULT false,
    from_name text COLLATE pg_catalog."default" NOT NULL,
    from_address text COLLATE pg_catalog."default" NOT NULL,
    time_received timestamp(0) with time zone NOT NULL,
    subject text COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    raw_mime text COLLATE pg_catalog."default",
    CONSTRAINT email_message_general_pkey PRIMARY KEY (em_id)
);

CREATE TABLE IF NOT EXISTS email_messages.forward_email
(
    forward_email_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    em_id bigint NOT NULL,
    forwarded_to text COLLATE pg_catalog."default" NOT NULL,
    success boolean NOT NULL DEFAULT true,
    forwarded_time timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT forward_email_pk PRIMARY KEY (forward_email_id)
);

CREATE TABLE IF NOT EXISTS email_messages.last_checked
(
    last_checked_pk bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    time_checked timestamp with time zone NOT NULL,
    check_now boolean DEFAULT false,
    email_id bigint NOT NULL,
    success boolean,
    CONSTRAINT last_checked_pk_fk PRIMARY KEY (last_checked_pk)
);

ALTER TABLE IF EXISTS email_messages.email_gmail
    ADD CONSTRAINT email_gmail_em_id_fkey FOREIGN KEY (em_id)
    REFERENCES email_messages.email_message_general (em_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS email_gmail_pk
    ON email_messages.email_gmail(em_id);


ALTER TABLE IF EXISTS email_messages.email_hotmail
    ADD CONSTRAINT email_hotmail_em_id_fkey FOREIGN KEY (em_id)
    REFERENCES email_messages.email_message_general (em_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS email_hotmail_em_id_idx
    ON email_messages.email_hotmail(em_id);


ALTER TABLE IF EXISTS email_messages.forward_email
    ADD CONSTRAINT em_id_fk FOREIGN KEY (em_id)
    REFERENCES email_messages.email_message_general (em_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
